var datos = [
    {
      obraSocial: { nombre: "AMFFA", href: "https://www.amffa.com.ar/" },
      membrete: "SI",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "ASADEF", href: "https://www.adef.org.ar/" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "ASOCIAR ART", href: "https://www.asociart.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: "FACAF",
    },
    {
      obraSocial: { nombre: "AVALIAN", href: "https://www.avalian.com/" },
      membrete: "SI",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "BANCO PROVINCIA", href: "http://www.amebpba.org.ar/" },
      membrete: "OFICIAL",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "CAJA DE ESCRIBANOS", href: "https://www.colescba.org.ar/portal/caja-seguridad-social" },
      membrete: "?",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "CASA", href: "https://www.casa.org.ar/" },
      membrete: "SI",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "CEMIN", href: "https://www.cemin.com/" },
      membrete: "?",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "COMEI", href: "https://www.comei.org.ar/" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "DASMI", href: "https://dasmi.org/" },
      membrete: "?",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "DASUTEN", href: "https://www.frbb.utn.edu.ar/obrasocial/" },
      membrete: "?",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "ENSALUD", href: "https://ensalud.org/novedades/" },
      membrete: "?",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: "COMPAÑÍA",
    },
    {
      obraSocial: { nombre: "GALENO", href: "https://www.galeno.com.ar/" },
      membrete: "NO",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "HOSPITAL AUSTRAL", href: "https://www.hospitalaustral.edu.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "IOMA", href: "https://www.ioma.gba.gob.ar/" },
      membrete: "OFICIAL",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "LA RECIPROCA", href: "https://www.lareciproca.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "COMPAÑÍA",
    },
    {
      obraSocial: { nombre: "LUIS PASTEUR", href: "https://www.oslpasteur.com.ar/portalHTML5/home.asp" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "MEDICUS", href: "https://medicus.com.ar/#/" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "MEDIFE", href: "https://www.medife.com.ar/" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "NIVEL SALUD", href: "https://www.facebook.com/NivelSaludOficial/?locale=es_LA" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: "SI",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OMINT", href: "https://www.omint.com.ar/PlanDeSalud/" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "OMINT DIABETES", href: "https://www.omint.com.ar/Website2/Default.aspx?tabid=4031" },
      membrete: "SI",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "IMED",
    },
    {
      obraSocial: { nombre: "OSCE (CERAMISTAS)", href: "https://www.prepagasar.com/obra-social/osce-cartilla" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSCEARA SALUD", href: "https://osceara.com.ar/" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSDE", href: "https://www.osde.com.ar/index.html#!homepage.html" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSDEPYM", href: "https://www.osdepym.com.ar/PortalCMS/app.htm" },
      membrete: "SI",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSFE", href: "https://www.osfe.org.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSFE DE CÁMARAS", href: "https://www.osfedecamaras.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSEIV", href: "http://www.oseiv.com.ar/" },
      membrete: "?",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSMATA", href: "https://osmata.com.ar/" },
      membrete: "OFICIAL",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSPE", href: "https://www.ospesalud.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSPIA", href: "https://www.ospia.org.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSPIM", href: "http://www.ospim.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSPIP (PLÁSTICOS)", href: "https://ospip.org.ar/" },
      membrete: "OFICIAL",
      principioActivo: " ",
      diagnostico: " ",
      validacion: " ",
    },
    {
      obraSocial: { nombre: "OSPLAD", href: "https://www.osplad.org.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSPM (MARÍTIMOS)", href: "https://ospm.com.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: "SI",
      validacion: "MIS VALIDACIONES",
    },
    {
      obraSocial: { nombre: "OSPSIP", href: "https://www.ospsip.org.ar/" },
      membrete: " ",
      principioActivo: "SI",
      diagnostico: " ",
      validacion: "COMPAÑÍA",
    },
    {
      obraSocial: { nombre: "PAMI", href: "https://www.pami.org.ar/" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "FACAF",
    },
    {
      obraSocial: { nombre: "PAP DESCUENTO", href: "https://www.bonospap.com.ar/" },
      membrete: " ",
      principioActivo: " ",
      diagnostico: " ",
      validacion: "MIS VALIDACIONES",
    },
    {
        obraSocial: { nombre: "PODER JUDICIAL", href: "https://www.ospjn.gov.ar/" },
        membrete: "?",
        principioActivo: "SI",
        diagnostico: " ",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "POLICIA FEDERAL", href: "https://supbienestar.gob.ar/" },
        membrete: "OFICIAL",
        principioActivo: "SI",
        diagnostico: " ",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "PREVENCIÓN SALUD", href: "https://www.prevencionsalud.com.ar/" },
        membrete: " ",
        principioActivo: "SI",
        diagnostico: " ",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "PROVINCIA ART", href: "https://www.provinciart.com.ar/" },
        membrete: " ",
        principioActivo: "SI",
        diagnostico: "SI",
        validacion: "FACAF",
      },
      {
        obraSocial: { nombre: "SANCOR SALUD", href: "https://www.sancorsalud.com.ar/" },
        membrete: "SI",
        principioActivo: "SI",
        diagnostico: "SI",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "SANIDAD (OPSA)", href: "https://www.sanidad.org.ar/obrasocial/obrasocial_home.aspx" },
        membrete: " ",
        principioActivo: " ",
        diagnostico: "SI",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "SWISS MEDICAL", href: "https://www.swissmedical.com.ar/prepagaclientes/" },
        membrete: "SI",
        principioActivo: " ",
        diagnostico: " ",
        validacion: "IMED",
      },
      {
        obraSocial: { nombre: "UNIÓN PERSONAL", href: "https://www.unionpersonal.com.ar/" },
        membrete: "SI",
        principioActivo: "SI",
        diagnostico: " ",
        validacion: " ",
      },
      {
        obraSocial: { nombre: "UNIÓN PERSONAL DIABETES", href: "https://www.https://www.unionpersonal.com.ar/files/descargas/carta_paciente_948_.pdf.com.ar/" },
        membrete: "SI",
        principioActivo: "SI",
        diagnostico: " ",
        validacion: "MIS VALIDACIONES",
      },
      {
        obraSocial: { nombre: "WILLIAM HOPE", href: "https://www.whope.com.ar/home" },
        membrete: " ",
        principioActivo: " ",
        diagnostico: " ",
        validacion: "IMED",
      },
];
